config/routes.rb
Rails.application.routes.draw do
  resources :contents
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'contents#index'
  get 'categories/listing/:id' => 'categories#listing'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :contents
end

app/models/content.rb
class Content < ApplicationRecord
  has_one :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def listing
    @category_name = Category.where(id: params[:id]).first.name
    @content_list = Content.where(category_id: params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.find_by_sql('SELECT contents.id,
                                    contents.title,
                                    contents.description,
                                    categories.id as category_id,
                                    categories.name as content_category
                                    FROM contents
                                    INNER JOIN categories
                                    ON contents.category_id = categories.id')
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @category_name = Category.where(id: @content.category_id)[0][:name]
  end

  # GET /contents/new
  def new
    @content = Content.new
    @category = Category.all
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:title, :description, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :category_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div id="menu-list">
  <h4>Menu: </h4>
  <h4><a href="/contents">content list</a></h4>
</div>

<h1>Categories List</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><a href="categories/listing/<%= category.id %>">list</a></td>
        <td><%= link_to 'view', category %></td>
        <td><%= link_to 'edit', edit_category_path(category) %></td>
        <td><%= link_to 'delete', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create new category', new_category_path %>

app/views/categories/listing.html.erb
<div id="menu-list">
  <h4>Menu: </h4>
  <h4><a href="/contents">content list</a></h4>
  <h4><a href="/categories">categories list</a></h4>
</div>

<h1>Contents of <%= @category_name %></h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @content_list.each do |content| %>
      <tr>
        <td><%= content.title %></td>
        <td>list</td>
        <td><%= link_to 'view', content %></td>
        <td><%= link_to 'edit', edit_content_path(content) %></td>
        <td><%= link_to 'delete', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', categories_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<div id="menu-list">
  <h4>Menu: </h4>
  <h4><a href="/contents">content list</a></h4>
  <h4><a href="/categories">categories list</a></h4>
</div>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
    <% if content.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

        <ul>
        <% content.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :content_title %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description, id: :content_description %>
    </div>

    <div class="field">
      <%= form.label :category %>
      <%= form.collection_select :category_id, Category.order(:name), :id, :name, :prompt => true, :selected => @content.category_id %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<div id="menu-list">
  <h4>Menu: </h4>
  <h4><a href="/categories">categories list</a></h4>
</div>

<h1>Contents List</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.title %></td>
        <td><%= content.description %></td>
        <td><a href="categories/listing/<%= content.category_id %>"><%= content.content_category %></a></td>
        <td><%= link_to 'view', content %></td>
        <td><%= link_to 'edit', edit_content_path(content) %></td>
        <td><%= link_to 'delete', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create new content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<div id="menu-list">
  <h4>Menu: </h4>
  <h4><a href="/contents">content list</a></h4>
  <h4><a href="/categories">categories list</a></h4>
</div>

<p>
  <strong>Title:</strong>
  <%= @content.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @content.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @category_name %>
</p>



<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>